version: '3'
services:
  db:
    image: "mdillon/postgis"
    environment:
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: garbage
    ports:
      - 5432:5432
    volumes: 
      - ./db_dumps:/docker-entrypoint-initdb.d