# Generated by Django 2.2.5 on 2019-09-28 01:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.TextField()),
                ('osm_id', models.TextField()),
                ('cci_id', models.TextField(null=True)),
                ('roi_type', models.TextField()),
                ('geometry', models.TextField()),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('line_string', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
            ],
        ),
    ]
