# Generated by Django 2.2.5 on 2019-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.TextField()),
                ('suitcase_id', models.TextField()),
                ('place_name', models.TextField()),
                ('place_type', models.TextField()),
                ('osm_id', models.TextField()),
                ('cci_id', models.TextField()),
                ('date', models.DateTimeField()),
                ('cci', models.FloatField()),
                ('rateCigarrettes', models.FloatField()),
                ('ratePapers', models.FloatField()),
                ('rateBottles', models.FloatField()),
                ('rateExcrements', models.FloatField()),
                ('rateSyringues', models.FloatField()),
                ('rateGums', models.FloatField()),
                ('rateLeaves', models.FloatField()),
                ('rateGrits', models.FloatField()),
                ('rateGlassDebris', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='roi',
            index=models.Index(fields=['osm_id'], name='garbage_map_osm_id_a280c8_idx'),
        ),
        migrations.AddIndex(
            model_name='roiinfo',
            index=models.Index(fields=['osm_id'], name='garbage_map_osm_id_55fe68_idx'),
        ),
    ]
