# Generated by Django 2.2.5 on 2019-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0002_auto_20190928_1010'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roi',
            index=models.Index(fields=['cci_id'], name='garbage_map_cci_id_a71a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='roiinfo',
            index=models.Index(fields=['cci_id'], name='garbage_map_cci_id_ee7856_idx'),
        ),
    ]
