# Generated by Django 2.2.5 on 2019-09-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("garbage_map", "0004_event_weather")]

    operations = [
        migrations.AddField(
            model_name="roi",
            name="average",
            field=models.FloatField(default=0),
            preserve_default=False,
        )
    ]
